### PR TITLE
Optimize for Firefox

### PR DESCRIPTION
**Pull request by LyubomirT**
This Pull Request removes Chrome-specific utility functions and downgrades the manifest to version 2 (because it's the one supported by Firefox for now).

> [!CAUTION]
> **PLEASE NOTE THAT IT'S BETTER TO CREATE A NEW BRANCH FOR THESE CHANGES AS THIS CAN DESTROY THE CHROME VERSION IF NOT MERGED PROPERLY**

### CODE REVIEW

**Comment by Santhoshmani1** [comment]
@LyubomirT  Thank you for your contribution to clear space.
I have created a seperate branch for maintaining the source code independently.

**Comment by Santhoshmani1** [comment]
Hey @LyubomirT Could you please send the pull request again. 
I merged the changes into main by mistake, now i have reverted them. 
I will be happy if you can please raise a new pull request.

**Comment by LyubomirT** [comment]
> Hey @LyubomirT Could you please send the pull request again. I merged the changes into main mistake, now i reverted them. I will be happy if you can please raise a new pull request.

Sure, just a moment...

**Comment by LyubomirT** [comment]
@Santhoshmani1 Seems like there is an issue with the revert process, or maybe I just need to wait a bit.
image

**Pull request merged**
